version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Darrell J Haynes Resume.doc
    - styles/*
    - images/*
    
