version: 0.1

phases:
  build:
    comments:
      - echo Nothing to do yet
artifacts:
  files:
    - images/*
    - styles/*
    - buildspec.yml
    - Darrell J Haynes Resume.doc
    - favicon.ico
    - index.html
